//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Hotel_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Hotel_Service.IHotelService")]
    public interface IHotelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetAllRooms", ReplyAction="http://tempuri.org/IHotelService/GetAllRoomsResponse")]
        System.Collections.Generic.List<System.Collections.Generic.List<string>> GetAllRooms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/GetAllRooms", ReplyAction="http://tempuri.org/IHotelService/GetAllRoomsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<System.Collections.Generic.List<string>>> GetAllRoomsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/Reserve_Room", ReplyAction="http://tempuri.org/IHotelService/Reserve_RoomResponse")]
        string Reserve_Room(string i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelService/Reserve_Room", ReplyAction="http://tempuri.org/IHotelService/Reserve_RoomResponse")]
        System.Threading.Tasks.Task<string> Reserve_RoomAsync(string i);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelServiceChannel : Hotel.Hotel_Service.IHotelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelServiceClient : System.ServiceModel.ClientBase<Hotel.Hotel_Service.IHotelService>, Hotel.Hotel_Service.IHotelService {
        
        public HotelServiceClient() {
        }
        
        public HotelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<System.Collections.Generic.List<string>> GetAllRooms() {
            return base.Channel.GetAllRooms();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<System.Collections.Generic.List<string>>> GetAllRoomsAsync() {
            return base.Channel.GetAllRoomsAsync();
        }
        
        public string Reserve_Room(string i) {
            return base.Channel.Reserve_Room(i);
        }
        
        public System.Threading.Tasks.Task<string> Reserve_RoomAsync(string i) {
            return base.Channel.Reserve_RoomAsync(i);
        }
    }
}
