//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel.Hotel_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Hotel_Service.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllRooms", ReplyAction="http://tempuri.org/IService1/GetAllRoomsResponse")]
        System.Collections.Generic.List<System.Collections.Generic.List<string>> GetAllRooms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllRooms", ReplyAction="http://tempuri.org/IService1/GetAllRoomsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<System.Collections.Generic.List<string>>> GetAllRoomsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Reserve_Room", ReplyAction="http://tempuri.org/IService1/Reserve_RoomResponse")]
        void Reserve_Room(string i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Reserve_Room", ReplyAction="http://tempuri.org/IService1/Reserve_RoomResponse")]
        System.Threading.Tasks.Task Reserve_RoomAsync(string i);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Hotel.Hotel_Service.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Hotel.Hotel_Service.IService1>, Hotel.Hotel_Service.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<System.Collections.Generic.List<string>> GetAllRooms() {
            return base.Channel.GetAllRooms();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<System.Collections.Generic.List<string>>> GetAllRoomsAsync() {
            return base.Channel.GetAllRoomsAsync();
        }
        
        public void Reserve_Room(string i) {
            base.Channel.Reserve_Room(i);
        }
        
        public System.Threading.Tasks.Task Reserve_RoomAsync(string i) {
            return base.Channel.Reserve_RoomAsync(i);
        }
    }
}
